import { Question, Difficulty, GrammarPoint } from "./types";

export const QUESTIONS: Question[] = [
  {
    id: "1",
    sentenceBefore: "",
    sentenceAfter: " tired, she still finished the report.",
    options: [
      { id: "a", text: "Though" },
      { id: "b", text: "Because" },
      { id: "c", text: "Unless" },
      { id: "d", text: "If" },
    ],
    correctOptionId: "a",
    difficulty: Difficulty.Junior,
    category: GrammarPoint.AdverbialClause,
    explanation: {
      correctAnswer: "Though",
      rule: "Though (虽然) 用于引导让步状语从句，表示尽管她很累，但她还是完成了报告。",
      example: "Though it was raining, they went for a walk. (尽管在下雨，他们还是去散步了。)",
      commonMistake: "使用 'Because' 会变成因为累所以完成报告，逻辑不通。",
    },
  },
  {
    id: "2",
    sentenceBefore: "The book ",
    sentenceAfter: " I bought yesterday is very interesting.",
    options: [
      { id: "a", text: "who" },
      { id: "b", text: "which" },
      { id: "c", text: "where" },
      { id: "d", text: "what" },
    ],
    correctOptionId: "b",
    difficulty: Difficulty.Junior,
    category: GrammarPoint.AttributiveClause,
    explanation: {
      correctAnswer: "which",
      rule: "在定语从句中，当先行词是物（the book）时，引导词使用 'which' 或 'that'。",
      example: "The car which he drives is red. (他开的那辆车是红色的。)",
      commonMistake: "对物使用 'who'，或者在定语从句中使用 'what'。",
    },
  },
  {
    id: "3",
    sentenceBefore: "",
    sentenceAfter: " from the top of the hill, the city looks beautiful.",
    options: [
      { id: "a", text: "Seen" },
      { id: "b", text: "Seeing" },
      { id: "c", text: "To see" },
      { id: "d", text: "Saw" },
    ],
    correctOptionId: "a",
    difficulty: Difficulty.Middle,
    category: GrammarPoint.NonFiniteVerb,
    explanation: {
      correctAnswer: "Seen",
      rule: "过去分词 'Seen' 用作状语，因为主句的主语 'the city' 与 'see' 之间是被动关系（城市是被看见的）。",
      example: "Written in simple English, the book is easy to read. (用简单的英语写成，这本书很容易读。)",
      commonMistake: "使用 'Seeing' 会表示城市主动在看，这是错误的。",
    },
  },
  {
    id: "4",
    sentenceBefore: "He is the man ",
    sentenceAfter: " son won the first prize.",
    options: [
      { id: "a", text: "who" },
      { id: "b", text: "whom" },
      { id: "c", text: "whose" },
      { id: "d", text: "that" },
    ],
    correctOptionId: "c",
    difficulty: Difficulty.Middle,
    category: GrammarPoint.AttributiveClause,
    explanation: {
      correctAnswer: "whose",
      rule: "'Whose' 在定语从句中表示所属关系（那个人的儿子）。",
      example: "I know a girl whose father is a doctor. (我认识一个女孩，她的父亲是医生。)",
      commonMistake: "使用不具备所属关系的 'who' 或 'whom'。",
    },
  },
  {
    id: "5",
    sentenceBefore: "I don't know ",
    sentenceAfter: " he will come or not.",
    options: [
      { id: "a", text: "if" },
      { id: "b", text: "whether" },
      { id: "c", text: "that" },
      { id: "d", text: "when" },
    ],
    correctOptionId: "b",
    difficulty: Difficulty.Junior,
    category: GrammarPoint.NounClause,
    explanation: {
      correctAnswer: "whether",
      rule: "当后面紧跟 'or not' 时，通常优先使用 'whether' 而非 'if' 来引导名词性从句。",
      example: "I'm not sure whether it will rain or not. (我不确定是否会下雨。)",
      commonMistake: "使用表示确定事实的 'that'。",
    },
  },
  {
    id: "6",
    sentenceBefore: "",
    sentenceAfter: " his homework, he went out to play.",
    options: [
      { id: "a", text: "Finished" },
      { id: "b", text: "Having finished" },
      { id: "c", text: "To finish" },
      { id: "d", text: "Finish" },
    ],
    correctOptionId: "b",
    difficulty: Difficulty.Senior,
    category: GrammarPoint.NonFiniteVerb,
    explanation: {
      correctAnswer: "Having finished",
      rule: "现在分词的完成式 'Having finished' 用于表示该动作在主句动作（出去玩）之前已经完成。",
      example: "Having had dinner, we went for a walk. (吃完晚饭后，我们去散步了。)",
      commonMistake: "使用 'Finished' 可能会被误解为被动意义，而这里是主动完成。",
    },
  },
  {
    id: "7",
    sentenceBefore: "This is the village ",
    sentenceAfter: " I lived ten years ago.",
    options: [
      { id: "a", text: "which" },
      { id: "b", text: "that" },
      { id: "c", text: "where" },
      { id: "d", text: "when" },
    ],
    correctOptionId: "c",
    difficulty: Difficulty.Middle,
    category: GrammarPoint.AttributiveClause,
    explanation: {
      correctAnswer: "where",
      rule: "'Where' 用作关系副词，指代地点（这个村庄），在从句中作地点状语（我住在那里）。",
      example: "The house where I was born is old. (我出生的那座房子很旧了。)",
      commonMistake: "直接使用 'which' 而不加介词（如 'in which'）。",
    },
  },
  {
    id: "8",
    sentenceBefore: "Weather ",
    sentenceAfter: ", we will go for a picnic.",
    options: [
      { id: "a", text: "permits" },
      { id: "b", text: "permitting" },
      { id: "c", text: "permitted" },
      { id: "d", text: "to permit" },
    ],
    correctOptionId: "b",
    difficulty: Difficulty.Senior,
    category: GrammarPoint.AbsoluteConstruction,
    explanation: {
      correctAnswer: "permitting",
      rule: "这是独立主格结构，'Weather' 是现在分词 'permitting' 的逻辑主语。",
      example: "Time permitting, I'll visit you. (如果时间允许，我会去看你。)",
      commonMistake: "使用 'permits' 会导致句子在没有连词的情况下出现两个谓语。",
    },
  },
  {
    id: "9",
    sentenceBefore: "He spoke so fast ",
    sentenceAfter: " I couldn't follow him.",
    options: [
      { id: "a", text: "that" },
      { id: "b", text: "than" },
      { id: "c", text: "as" },
      { id: "d", text: "which" },
    ],
    correctOptionId: "a",
    difficulty: Difficulty.Junior,
    category: GrammarPoint.AdverbialClause,
    explanation: {
      correctAnswer: "that",
      rule: "'so... that...' 结构用于引导结果状语从句，表示“如此...以至于...”。",
      example: "It was so hot that we stayed indoors. (天气太热了，以至于我们都待在室内。)",
      commonMistake: "将 'so... that' 与 'so... as to' 混淆。",
    },
  },
  {
    id: "10",
    sentenceBefore: "The teacher suggested that we ",
    sentenceAfter: " the work on time.",
    options: [
      { id: "a", text: "finished" },
      { id: "b", text: "finish" },
      { id: "c", text: "will finish" },
      { id: "d", text: "to finish" },
    ],
    correctOptionId: "b",
    difficulty: Difficulty.Middle,
    category: GrammarPoint.NounClause,
    explanation: {
      correctAnswer: "finish",
      rule: "在表示建议、要求、命令的动词（如 suggest）后的宾语从句中，谓语动词用虚拟语气：(should) + 动词原形。",
      example: "I suggest that he go at once. (我建议他立刻就走。)",
      commonMistake: "根据时态错误地使用 'finished' 或 'will finish'。",
    },
  },
];
